name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: List in ${{ github.workspace }}
        run: ls -la ${{ github.workspace }}
      - name: List in ~
        run: ls -la ~

      - name: Build with Maven
        run: mvn verify -e -B -V

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '${{ github.workspace }}target/surefire-reports/TEST*.xml'
#      - name: Add coverage to PR
#        id: jacoco
#        uses: madrapps/jacoco-report@v1.3
#        with:
#          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
