name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: List in ${{ github.workspace }}
        run: ls -la ${{ github.workspace }}
      - name: List in ~
        run: ls -la ~
      - name: List in maven-it-extension
        run: ls -la maven-it-extension

      - name: Build with Maven
        run: mvn verify -e -B -V
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: 'Publish Test Results'
          working-directory: ${{ github.workspace }}
          path: |
            ${{ github.workspace }}/target/surefire-reports/*.xml
          reporter: 'java-junit'

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
