name: CI

on: [pull_request,push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: List in ${{ github.workspace }}
        run: ls -la ${{ github.workspace }}
      - name: List in ~
        run: ls -la ~

      - name: Build with Maven
        run: mvn verify -e -B -V -Dmaven.test.failure.ignore=true


      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        id: unit-test-results
        if: always()
        with:
          check_name: Test Results
          comment_title: Test Results
          junit_files: |
            ${{ github.workspace }}/target/surefire-reports/TEST-*.xml

      - name: Publish Integration Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        id: integration-test-results
        if: always()
        with:
          check_name: Integration Test Results
          comment_title: Integration Test Results
          junit_files: |
            ${{ github.workspace }}/target/failsafe-reports/TEST-*.xml

      - name: Set badge color Unit Tests
        shell: bash
        run: |
          case ${{ fromJSON( steps.unit-test-results.outputs.json ).conclusion }} in
            success)
              echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
              ;;
            failure)
              echo "BADGE_COLOR=800000" >> $GITHUB_ENV
              ;;
            neutral)
              echo "BADGE_COLOR=696969" >> $GITHUB_ENV
              ;;
          esac

      - name: Create badge - Unit Tests
        uses: emibcn/badge-action@d6f51ff11b5c3382b3b88689ae2d6db22d9737d1
        with:
          label: Tests
          status: '${{ fromJSON( steps.unit-test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.unit-test-results.outputs.json ).formatted.stats.runs }} runs: ${{ fromJSON( steps.unit-test-results.outputs.json ).conclusion }}'
          color: ${{ env.BADGE_COLOR }}
          path: badge-unit-test.svg

      - name: Upload badge to Gist - Unit Tests
        # Upload only for main branch
        if: >
          github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main' ||
          github.event_name != 'workflow_run' && github.ref == 'refs/heads/main'
        uses: andymckay/append-gist-action@1fbfbbce708a39bd45846f0955ed5521f2099c6d
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/khmarbaise/32a3c56ef9a10798e755e2c1e921ab85
          file: badge-unit-test.svg

      - name: Set badge color Integration Tests
        shell: bash
        run: |
          case ${{ fromJSON( steps.integration-test-results.outputs.json ).conclusion }} in
            success)
              echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
              ;;
            failure)
              echo "BADGE_COLOR=800000" >> $GITHUB_ENV
              ;;
            neutral)
              echo "BADGE_COLOR=696969" >> $GITHUB_ENV
              ;;
          esac

      - name: Create badge - Integration Tests
        uses: emibcn/badge-action@d6f51ff11b5c3382b3b88689ae2d6db22d9737d1
        with:
          label: Integration-Tests
          status: '${{ fromJSON( steps.integration-test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.integration-test-results.outputs.json ).formatted.stats.runs }} runs: ${{ fromJSON( steps.integration-test-results.outputs.json ).conclusion }}'
          color: ${{ env.BADGE_COLOR }}
          path: badge-integration-test.svg

      - name: Upload badge to Gist - Integration Tests
        # Upload only for main branch
        if: >
          github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main' ||
          github.event_name != 'workflow_run' && github.ref == 'refs/heads/main'
        uses: andymckay/append-gist-action@1fbfbbce708a39bd45846f0955ed5521f2099c6d
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/khmarbaise/87c4e60bdea4a6ad1c0d80682779784c
          file: badge-integration-test.svg

#      - name: Add coverage to PR
#        id: jacoco
#        uses: madrapps/jacoco-report@v1.3
#        with:
#          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
